config/routes.rb
Rails.application.routes.draw do

  resources :stamps do
    collection do
      post 'upload', to: "watermarks#create"
    end
    member do 
      get :preview
    end
  end

  resources :stamped_images, only: [:index, :show]
  
  controller :sessions do  
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  root to: 'home#index'
end

app/models/stamp.rb
class Stamp < ActiveRecord::Base

  POSITIONS = [
    Magick::NorthWestGravity.to_i,  Magick::NorthGravity.to_i,  Magick::NorthEastGravity.to_i,
    Magick::WestGravity.to_i,       Magick::CenterGravity.to_i, Magick::EastGravity.to_i,
    Magick::SouthWestGravity.to_i,  Magick::SouthGravity.to_i,  Magick::SouthEastGravity.to_i
  ]

  belongs_to :shop
  belongs_to :watermark

  validates :shop, presence: true
  validates :watermark, presence: true
  validates :rotate, numericality: {greater_than_or_equal_to: -360, less_than_or_equal_to: 360}
  validates :transparency, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 1}
  validates :position, inclusion: POSITIONS

  before_validation :assign_defaults, on: :create

  private

    def assign_defaults
      self.rotate = 0 if self.rotate.blank?
      self.transparency = 1 if self.transparency.blank?
      self.position = Magick::CenterGravity.to_i if self.position.blank?
      true
    end
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  around_filter :shopify_session
  before_filter :require_shop
  before_action :set_stamp, only: [:show, :edit, :update, :destroy, :preview]

  # GET /stamps
  # GET /stamps.json
  def index
    @stamps = @current_shop.stamps
  end

  # GET /stamps/1
  # GET /stamps/1.json
  def show
  end

  # GET /stamps/new
  def new
    @stamp = @current_shop.stamps.new
  end

  # GET /stamps/1/edit
  def edit
  end

  # POST /stamps
  # POST /stamps.json
  def create
    @stamp = @current_shop.stamps.new(stamp_params)

    respond_to do |format|
      if @stamp.save!
        
        @shop.previews.generate_previews

        format.html { redirect_to @stamp, notice: 'Stamp was successfully created.' }
        format.json { render :show, status: :created, location: @stamp }
      else
        format.html { render :new }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stamps/1
  # PATCH/PUT /stamps/1.json
  def update
    respond_to do |format|
      if @stamp.update(stamp_params)
        format.html { redirect_to @stamp, notice: 'Stamp was successfully updated.' }
        format.json { render :show, status: :ok, location: @stamp }
      else
        format.html { render :edit }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stamps/1
  # DELETE /stamps/1.json
  def destroy
    @stamp.destroy
    respond_to do |format|
      format.html { redirect_to stamps_url, notice: 'Stamp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    @product_images = @current_shop.product_images.sample(3)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stamp
      @stamp = @current_shop.stamps.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stamp_params
      params.require(:stamp).permit(:name, :watermark_id, :rotate, :transparency, :position, :tiled)
    end
end

app/helpers/stamps_helper.rb
module StampsHelper

  def preview_image_for(shop)
    shop.product_images.first.try(:source_url) || "placeholder_product.jpg"
  end

end

app/views/stamps/_form.html.erb
<%= simple_form_for(@stamp) do |f| %>

  <%= f.input :name %>
  <%= f.input :rotate %>
  <%= f.input :transparency %>
  <%= f.input :position %>
  <%= f.input :tiled %>
  
  <%= f.button :submit, class: "btn-success" %>

<% end %>

app/views/stamps/edit.html.erb
<h1>Editing stamp</h1>

<%= render 'form' %>

<%= link_to 'Show', @stamp %> |
<%= link_to 'Back', stamps_path %>

app/views/stamps/index.html.erb
<h1>Listing stamps</h1>

<%= link_to 'New Stamp', new_stamp_path %>

app/views/stamps/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Create Your Wetstamp</h1>
  </div>
</div>

<div class="row" id="wetstamp-form">

  <div class="col-xs-12 col-md-8 col-md-push-4">

    <h3>
      Live Preview
      <small>
        <span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="top" 
        title="The live preview is a general guide. You can see a processed preview by clicking finalize.">
        </span>
      </small>
    </h3>

    <div class="preview text-center" id="watermark-preview">
      <div id="product-image">
        <%= image_tag preview_image_for(current_shop) %>
        <div id="watermark">
        </div>
      </div>
    </div>

    <div class="visible-md visible-lg">
      <p>
        <button class="btn btn-success btn-lg btn-block submit">Preview &gt;</button>
      </p>
    </div>

  </div>

  <div class="col-xs-12 col-md-4 col-md-pull-8">
    <div class="row">
      <div class="col-xs-12">
        <%= form_for(Watermark.new, url: upload_stamps_path, html: {multipart: :true}, remote: true) do |f| %>

          <div class="field">
            <h3>1) Upload your Stamp</h3>
            <div class="form-group">
              <%= f.file_field :image, accept: "image/*" %>
            </div>
          </div>

        <% end %>
      </div>

      <div class="col-xs-12">
        <h3>2) Choose a Style</h3>
        <div class="row watermark-presets">
          
          <a data-role="watermark-preset" 
            data-class="bottom right"
            data-rotate="0" 
            data-position="<%= Magick::SouthEastGravity.to_i %>"
            data-tiled="0"
            data-no-turbolink>
            <%= image_tag "presets/bottom_right.png", alt: "Bottom Right" %>
          </a>

          <a data-role="watermark-preset"
            data-class="bottom left vertical"
            data-rotate="-90"
            data-position="<%= Magick::SouthWestGravity.to_i %>"
            data-tiled="0"
            data-no-turbolink>
            <%= image_tag "presets/bottom_left_vertical.png", alt: "Bottom Left, Vertical" %>
          </a>


          <a data-role="watermark-preset" 
            data-class="bottom left"
            data-rotate="0" 
            data-position="<%= Magick::SouthWestGravity.to_i %>"
            data-tiled="0"
            data-no-turbolink>
            <%= image_tag "presets/bottom_left.png", alt: "Bottom Left" %>
          </a>

          <a data-role="watermark-preset"
            data-class="center neg45deg"
            data-rotate="-45"
            data-position="<%= Magick::CenterGravity.to_i %>"
            data-tiled="0"
            data-no-turbolink>
            <%= image_tag "presets/center_neg45deg.png", alt: "Centered, negative 45 degree angle" %>
          </a>

          <a data-role="watermark-preset"
            data-class="center"
            data-rotate="0"
            data-position="<%= Magick::CenterGravity.to_i %>"
            data-tiled="0"
            data-no-turbolink>
            <%= image_tag "presets/center_horizontal.png", alt: "Centered and Horizontal" %>
          </a>

          <a data-role="watermark-preset"
            data-class="center neg45deg"
            data-rotate="-45"
            data-position="<%= Magick::CenterGravity.to_i %>"
            data-tiled="1"
            data-no-turbolink>
            <%= image_tag "presets/tiled_neg45deg.png", alt: "Negative 45 degrees, and tiled repeatedly" %>
          </a>
        </div>
      </div>

      <div class="col-xs-12 padding-bottom">
        <h3>3) Tweak it</h3>

        <div class="row text-center">
          <div class="col-xs-12 col-sm-6">
            
            <label for="stamp_size">Size</label><br />

            <button class="btn btn-primary btn-half delta" type="button" data-delta="-5" data-for="size">
              <span class="glyphicon glyphicon-minus"></span>
            </button>
            <button class="btn btn-primary btn-half delta" type="button" data-delta="5" data-for="size">
              <span class="glyphicon glyphicon-plus"></span>
            </button>

          </div>
          <div class="col-xs-12 col-sm-6">
            
            <label for="stamp_transparency">Transparency</label><br />

            <button class="btn btn-primary btn-half delta" type="button" data-delta="0.05" data-for="transparency">
              <span class="glyphicon glyphicon-minus"></span>
            </button>
            <button class="btn btn-primary btn-half delta" type="button" data-delta="-0.05" data-for="transparency">
              <span class="glyphicon glyphicon-plus"></span>
            </button>

          </div>
        </div>
        
      </div>

      <div class="col-xs-12 pull-right hidden-md hidden-lg">
        <p>
          <button class="btn btn-success btn-lg btn-block submit">Finalize &gt;</button>
        </p>
      </div>

    </div>
  </div>

</div>

app/views/stamps/preview.html.erb
<h1>Final Preview</h1>

<div class="row">
  <div class="col-xs-12">
    <p>
      Please wait while we generate some preview images.
    </p>
  </div>
</div>


<div class="row">
  <div class="col-xs-12 js-stamp-preview" data-url="<%= stamped_images_url(stamp: @stamp, format: :json) %>">
  </div>
</div>


<div class="row">
  <div class="col-xs-12">
    <h2>Ready to go?</h2>
    <p>
      If you're happy with how your watermark looks, click Apply My Watermark below.
    </p>
    <p>
      <button class="btn btn-success btn-lg btn-block submit">Apply My Watermark</button>
    </p>
    <hr />
    <h4>How long will it take?</h4>
    <p>Each image usually takes one or two seconds to watermark and upload to your store.</p>
    <h4>Is it permanent?</h4>
    <p>
      No. We save your original images, so if something isn't right you can undo your watermark.<br />
      It costs the same amount to remove a watermark as is does to apply a watermark.
    </p>
  </div>
</div>

app/views/stamps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop:</strong>
  <%= @stamp.shop.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @stamp.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @stamp.watermark.image %>
</p>

<p>
  <strong>Rotate:</strong>
  <%= @stamp.rotate %>
</p>

<p>
  <strong>Transparency:</strong>
  <%= @stamp.transparency %>
</p>

<p>
  <strong>Position:</strong>
  <%= @stamp.position %>
</p>

<p>
  <strong>Tiled:</strong>
  <%= @stamp.tiled %>
</p>

<%= link_to 'Edit', edit_stamp_path(@stamp) %> |
<%= link_to 'Back', stamps_path %>